import "./globals.css";
import { Montserrat } from "next/font/google";
import Layout from "@/components/Nav";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR" className={montserrat.variable}>
      <body className={montserrat.variable}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
